/** Transforme un code pays ISO 3166-1 alpha-2 (ex "FR") en emoji drapeau (🇫🇷). */
export function countryFlag(code: string): string {
  if (!/^[A-Z]{2}$/.test(code)) return "🏳️"
  const base = 0x1f1e6 // 'A' régional indicateur
  const chars = [...code].map((c) => base + (c.charCodeAt(0) - 65))
  return String.fromCodePoint(...chars)
}

export interface Country {
  code: string
  fr: string
  en: string
}

// Liste complète des pays et territoires ISO 3166-1 (~250 entrées), pour être
// le plus inclusif possible dans le choix du drapeau du classement.
export const COUNTRIES: Country[] = [
  { code: "AD", fr: "Andorre", en: "Andorra" },
  { code: "AE", fr: "Émirats arabes unis", en: "United Arab Emirates" },
  { code: "AF", fr: "Afghanistan", en: "Afghanistan" },
  { code: "AG", fr: "Antigua-et-Barbuda", en: "Antigua & Barbuda" },
  { code: "AI", fr: "Anguilla", en: "Anguilla" },
  { code: "AL", fr: "Albanie", en: "Albania" },
  { code: "AM", fr: "Arménie", en: "Armenia" },
  { code: "AO", fr: "Angola", en: "Angola" },
  { code: "AQ", fr: "Antarctique", en: "Antarctica" },
  { code: "AR", fr: "Argentine", en: "Argentina" },
  { code: "AS", fr: "Samoa américaines", en: "American Samoa" },
  { code: "AT", fr: "Autriche", en: "Austria" },
  { code: "AU", fr: "Australie", en: "Australia" },
  { code: "AW", fr: "Aruba", en: "Aruba" },
  { code: "AX", fr: "Îles Åland", en: "Åland Islands" },
  { code: "AZ", fr: "Azerbaïdjan", en: "Azerbaijan" },
  { code: "BA", fr: "Bosnie-Herzégovine", en: "Bosnia & Herzegovina" },
  { code: "BB", fr: "Barbade", en: "Barbados" },
  { code: "BD", fr: "Bangladesh", en: "Bangladesh" },
  { code: "BE", fr: "Belgique", en: "Belgium" },
  { code: "BF", fr: "Burkina Faso", en: "Burkina Faso" },
  { code: "BG", fr: "Bulgarie", en: "Bulgaria" },
  { code: "BH", fr: "Bahreïn", en: "Bahrain" },
  { code: "BI", fr: "Burundi", en: "Burundi" },
  { code: "BJ", fr: "Bénin", en: "Benin" },
  { code: "BL", fr: "Saint-Barthélemy", en: "St. Barthélemy" },
  { code: "BM", fr: "Bermudes", en: "Bermuda" },
  { code: "BN", fr: "Brunei", en: "Brunei" },
  { code: "BO", fr: "Bolivie", en: "Bolivia" },
  { code: "BQ", fr: "Pays-Bas caribéens", en: "Caribbean Netherlands" },
  { code: "BR", fr: "Brésil", en: "Brazil" },
  { code: "BS", fr: "Bahamas", en: "Bahamas" },
  { code: "BT", fr: "Bhoutan", en: "Bhutan" },
  { code: "BV", fr: "Île Bouvet", en: "Bouvet Island" },
  { code: "BW", fr: "Botswana", en: "Botswana" },
  { code: "BY", fr: "Biélorussie", en: "Belarus" },
  { code: "BZ", fr: "Belize", en: "Belize" },
  { code: "CA", fr: "Canada", en: "Canada" },
  { code: "CC", fr: "Îles Cocos", en: "Cocos (Keeling) Islands" },
  { code: "CD", fr: "Congo-Kinshasa", en: "Congo - Kinshasa" },
  { code: "CF", fr: "République centrafricaine", en: "Central African Republic" },
  { code: "CG", fr: "Congo-Brazzaville", en: "Congo - Brazzaville" },
  { code: "CH", fr: "Suisse", en: "Switzerland" },
  { code: "CI", fr: "Côte d’Ivoire", en: "Côte d’Ivoire" },
  { code: "CK", fr: "Îles Cook", en: "Cook Islands" },
  { code: "CL", fr: "Chili", en: "Chile" },
  { code: "CM", fr: "Cameroun", en: "Cameroon" },
  { code: "CN", fr: "Chine", en: "China" },
  { code: "CO", fr: "Colombie", en: "Colombia" },
  { code: "CR", fr: "Costa Rica", en: "Costa Rica" },
  { code: "CU", fr: "Cuba", en: "Cuba" },
  { code: "CV", fr: "Cap-Vert", en: "Cape Verde" },
  { code: "CW", fr: "Curaçao", en: "Curaçao" },
  { code: "CX", fr: "Île Christmas", en: "Christmas Island" },
  { code: "CY", fr: "Chypre", en: "Cyprus" },
  { code: "CZ", fr: "Tchéquie", en: "Czechia" },
  { code: "DE", fr: "Allemagne", en: "Germany" },
  { code: "DJ", fr: "Djibouti", en: "Djibouti" },
  { code: "DK", fr: "Danemark", en: "Denmark" },
  { code: "DM", fr: "Dominique", en: "Dominica" },
  { code: "DO", fr: "République dominicaine", en: "Dominican Republic" },
  { code: "DZ", fr: "Algérie", en: "Algeria" },
  { code: "EC", fr: "Équateur", en: "Ecuador" },
  { code: "EE", fr: "Estonie", en: "Estonia" },
  { code: "EG", fr: "Égypte", en: "Egypt" },
  { code: "EH", fr: "Sahara occidental", en: "Western Sahara" },
  { code: "ER", fr: "Érythrée", en: "Eritrea" },
  { code: "ES", fr: "Espagne", en: "Spain" },
  { code: "ET", fr: "Éthiopie", en: "Ethiopia" },
  { code: "FI", fr: "Finlande", en: "Finland" },
  { code: "FJ", fr: "Fidji", en: "Fiji" },
  { code: "FK", fr: "Îles Malouines", en: "Falkland Islands" },
  { code: "FM", fr: "Micronésie", en: "Micronesia" },
  { code: "FO", fr: "Îles Féroé", en: "Faroe Islands" },
  { code: "FR", fr: "France", en: "France" },
  { code: "GA", fr: "Gabon", en: "Gabon" },
  { code: "GB", fr: "Royaume-Uni", en: "United Kingdom" },
  { code: "GD", fr: "Grenade", en: "Grenada" },
  { code: "GE", fr: "Géorgie", en: "Georgia" },
  { code: "GF", fr: "Guyane française", en: "French Guiana" },
  { code: "GG", fr: "Guernesey", en: "Guernsey" },
  { code: "GH", fr: "Ghana", en: "Ghana" },
  { code: "GI", fr: "Gibraltar", en: "Gibraltar" },
  { code: "GL", fr: "Groenland", en: "Greenland" },
  { code: "GM", fr: "Gambie", en: "Gambia" },
  { code: "GN", fr: "Guinée", en: "Guinea" },
  { code: "GP", fr: "Guadeloupe", en: "Guadeloupe" },
  { code: "GQ", fr: "Guinée équatoriale", en: "Equatorial Guinea" },
  { code: "GR", fr: "Grèce", en: "Greece" },
  { code: "GS", fr: "Géorgie du Sud-et-les Îles Sandwich du Sud", en: "South Georgia & South Sandwich Islands" },
  { code: "GT", fr: "Guatemala", en: "Guatemala" },
  { code: "GU", fr: "Guam", en: "Guam" },
  { code: "GW", fr: "Guinée-Bissau", en: "Guinea-Bissau" },
  { code: "GY", fr: "Guyana", en: "Guyana" },
  { code: "HK", fr: "R.A.S. chinoise de Hong Kong", en: "Hong Kong SAR China" },
  { code: "HM", fr: "Îles Heard-et-MacDonald", en: "Heard & McDonald Islands" },
  { code: "HN", fr: "Honduras", en: "Honduras" },
  { code: "HR", fr: "Croatie", en: "Croatia" },
  { code: "HT", fr: "Haïti", en: "Haiti" },
  { code: "HU", fr: "Hongrie", en: "Hungary" },
  { code: "ID", fr: "Indonésie", en: "Indonesia" },
  { code: "IE", fr: "Irlande", en: "Ireland" },
  { code: "IL", fr: "Israël", en: "Israel" },
  { code: "IM", fr: "Île de Man", en: "Isle of Man" },
  { code: "IN", fr: "Inde", en: "India" },
  { code: "IO", fr: "Territoire britannique de l’océan Indien", en: "British Indian Ocean Territory" },
  { code: "IQ", fr: "Irak", en: "Iraq" },
  { code: "IR", fr: "Iran", en: "Iran" },
  { code: "IS", fr: "Islande", en: "Iceland" },
  { code: "IT", fr: "Italie", en: "Italy" },
  { code: "JE", fr: "Jersey", en: "Jersey" },
  { code: "JM", fr: "Jamaïque", en: "Jamaica" },
  { code: "JO", fr: "Jordanie", en: "Jordan" },
  { code: "JP", fr: "Japon", en: "Japan" },
  { code: "KE", fr: "Kenya", en: "Kenya" },
  { code: "KG", fr: "Kirghizstan", en: "Kyrgyzstan" },
  { code: "KH", fr: "Cambodge", en: "Cambodia" },
  { code: "KI", fr: "Kiribati", en: "Kiribati" },
  { code: "KM", fr: "Comores", en: "Comoros" },
  { code: "KN", fr: "Saint-Christophe-et-Niévès", en: "St. Kitts & Nevis" },
  { code: "KP", fr: "Corée du Nord", en: "North Korea" },
  { code: "KR", fr: "Corée du Sud", en: "South Korea" },
  { code: "KW", fr: "Koweït", en: "Kuwait" },
  { code: "KY", fr: "Îles Caïmans", en: "Cayman Islands" },
  { code: "KZ", fr: "Kazakhstan", en: "Kazakhstan" },
  { code: "LA", fr: "Laos", en: "Laos" },
  { code: "LB", fr: "Liban", en: "Lebanon" },
  { code: "LC", fr: "Sainte-Lucie", en: "St. Lucia" },
  { code: "LI", fr: "Liechtenstein", en: "Liechtenstein" },
  { code: "LK", fr: "Sri Lanka", en: "Sri Lanka" },
  { code: "LR", fr: "Liberia", en: "Liberia" },
  { code: "LS", fr: "Lesotho", en: "Lesotho" },
  { code: "LT", fr: "Lituanie", en: "Lithuania" },
  { code: "LU", fr: "Luxembourg", en: "Luxembourg" },
  { code: "LV", fr: "Lettonie", en: "Latvia" },
  { code: "LY", fr: "Libye", en: "Libya" },
  { code: "MA", fr: "Maroc", en: "Morocco" },
  { code: "MC", fr: "Monaco", en: "Monaco" },
  { code: "MD", fr: "Moldavie", en: "Moldova" },
  { code: "ME", fr: "Monténégro", en: "Montenegro" },
  { code: "MF", fr: "Saint-Martin", en: "St. Martin" },
  { code: "MG", fr: "Madagascar", en: "Madagascar" },
  { code: "MH", fr: "Îles Marshall", en: "Marshall Islands" },
  { code: "MK", fr: "Macédoine du Nord", en: "North Macedonia" },
  { code: "ML", fr: "Mali", en: "Mali" },
  { code: "MM", fr: "Myanmar (Birmanie)", en: "Myanmar (Burma)" },
  { code: "MN", fr: "Mongolie", en: "Mongolia" },
  { code: "MO", fr: "R.A.S. chinoise de Macao", en: "Macao SAR China" },
  { code: "MP", fr: "Îles Mariannes du Nord", en: "Northern Mariana Islands" },
  { code: "MQ", fr: "Martinique", en: "Martinique" },
  { code: "MR", fr: "Mauritanie", en: "Mauritania" },
  { code: "MS", fr: "Montserrat", en: "Montserrat" },
  { code: "MT", fr: "Malte", en: "Malta" },
  { code: "MU", fr: "Maurice", en: "Mauritius" },
  { code: "MV", fr: "Maldives", en: "Maldives" },
  { code: "MW", fr: "Malawi", en: "Malawi" },
  { code: "MX", fr: "Mexique", en: "Mexico" },
  { code: "MY", fr: "Malaisie", en: "Malaysia" },
  { code: "MZ", fr: "Mozambique", en: "Mozambique" },
  { code: "NA", fr: "Namibie", en: "Namibia" },
  { code: "NC", fr: "Nouvelle-Calédonie", en: "New Caledonia" },
  { code: "NE", fr: "Niger", en: "Niger" },
  { code: "NF", fr: "Île Norfolk", en: "Norfolk Island" },
  { code: "NG", fr: "Nigeria", en: "Nigeria" },
  { code: "NI", fr: "Nicaragua", en: "Nicaragua" },
  { code: "NL", fr: "Pays-Bas", en: "Netherlands" },
  { code: "NO", fr: "Norvège", en: "Norway" },
  { code: "NP", fr: "Népal", en: "Nepal" },
  { code: "NR", fr: "Nauru", en: "Nauru" },
  { code: "NU", fr: "Niue", en: "Niue" },
  { code: "NZ", fr: "Nouvelle-Zélande", en: "New Zealand" },
  { code: "OM", fr: "Oman", en: "Oman" },
  { code: "PA", fr: "Panama", en: "Panama" },
  { code: "PE", fr: "Pérou", en: "Peru" },
  { code: "PF", fr: "Polynésie française", en: "French Polynesia" },
  { code: "PG", fr: "Papouasie-Nouvelle-Guinée", en: "Papua New Guinea" },
  { code: "PH", fr: "Philippines", en: "Philippines" },
  { code: "PK", fr: "Pakistan", en: "Pakistan" },
  { code: "PL", fr: "Pologne", en: "Poland" },
  { code: "PM", fr: "Saint-Pierre-et-Miquelon", en: "St. Pierre & Miquelon" },
  { code: "PN", fr: "Îles Pitcairn", en: "Pitcairn Islands" },
  { code: "PR", fr: "Porto Rico", en: "Puerto Rico" },
  { code: "PS", fr: "Territoires palestiniens", en: "Palestinian Territories" },
  { code: "PT", fr: "Portugal", en: "Portugal" },
  { code: "PW", fr: "Palaos", en: "Palau" },
  { code: "PY", fr: "Paraguay", en: "Paraguay" },
  { code: "QA", fr: "Qatar", en: "Qatar" },
  { code: "RE", fr: "La Réunion", en: "Réunion" },
  { code: "RO", fr: "Roumanie", en: "Romania" },
  { code: "RS", fr: "Serbie", en: "Serbia" },
  { code: "RU", fr: "Russie", en: "Russia" },
  { code: "RW", fr: "Rwanda", en: "Rwanda" },
  { code: "SA", fr: "Arabie saoudite", en: "Saudi Arabia" },
  { code: "SB", fr: "Îles Salomon", en: "Solomon Islands" },
  { code: "SC", fr: "Seychelles", en: "Seychelles" },
  { code: "SD", fr: "Soudan", en: "Sudan" },
  { code: "SE", fr: "Suède", en: "Sweden" },
  { code: "SG", fr: "Singapour", en: "Singapore" },
  { code: "SH", fr: "Sainte-Hélène", en: "St. Helena" },
  { code: "SI", fr: "Slovénie", en: "Slovenia" },
  { code: "SJ", fr: "Svalbard et Jan Mayen", en: "Svalbard & Jan Mayen" },
  { code: "SK", fr: "Slovaquie", en: "Slovakia" },
  { code: "SL", fr: "Sierra Leone", en: "Sierra Leone" },
  { code: "SM", fr: "Saint-Marin", en: "San Marino" },
  { code: "SN", fr: "Sénégal", en: "Senegal" },
  { code: "SO", fr: "Somalie", en: "Somalia" },
  { code: "SR", fr: "Suriname", en: "Suriname" },
  { code: "SS", fr: "Soudan du Sud", en: "South Sudan" },
  { code: "ST", fr: "Sao Tomé-et-Principe", en: "São Tomé & Príncipe" },
  { code: "SV", fr: "Salvador", en: "El Salvador" },
  { code: "SX", fr: "Saint-Martin (partie néerlandaise)", en: "Sint Maarten" },
  { code: "SY", fr: "Syrie", en: "Syria" },
  { code: "SZ", fr: "Eswatini", en: "Eswatini" },
  { code: "TC", fr: "Îles Turques-et-Caïques", en: "Turks & Caicos Islands" },
  { code: "TD", fr: "Tchad", en: "Chad" },
  { code: "TF", fr: "Terres australes françaises", en: "French Southern Territories" },
  { code: "TG", fr: "Togo", en: "Togo" },
  { code: "TH", fr: "Thaïlande", en: "Thailand" },
  { code: "TJ", fr: "Tadjikistan", en: "Tajikistan" },
  { code: "TK", fr: "Tokelau", en: "Tokelau" },
  { code: "TL", fr: "Timor oriental", en: "Timor-Leste" },
  { code: "TM", fr: "Turkménistan", en: "Turkmenistan" },
  { code: "TN", fr: "Tunisie", en: "Tunisia" },
  { code: "TO", fr: "Tonga", en: "Tonga" },
  { code: "TR", fr: "Turquie", en: "Türkiye" },
  { code: "TT", fr: "Trinité-et-Tobago", en: "Trinidad & Tobago" },
  { code: "TV", fr: "Tuvalu", en: "Tuvalu" },
  { code: "TW", fr: "Taïwan", en: "Taiwan" },
  { code: "TZ", fr: "Tanzanie", en: "Tanzania" },
  { code: "UA", fr: "Ukraine", en: "Ukraine" },
  { code: "UG", fr: "Ouganda", en: "Uganda" },
  { code: "UM", fr: "Îles mineures éloignées des États-Unis", en: "U.S. Outlying Islands" },
  { code: "US", fr: "États-Unis", en: "United States" },
  { code: "UY", fr: "Uruguay", en: "Uruguay" },
  { code: "UZ", fr: "Ouzbékistan", en: "Uzbekistan" },
  { code: "VA", fr: "État de la Cité du Vatican", en: "Vatican City" },
  { code: "VC", fr: "Saint-Vincent-et-les Grenadines", en: "St. Vincent & Grenadines" },
  { code: "VE", fr: "Venezuela", en: "Venezuela" },
  { code: "VG", fr: "Îles Vierges britanniques", en: "British Virgin Islands" },
  { code: "VI", fr: "Îles Vierges des États-Unis", en: "U.S. Virgin Islands" },
  { code: "VN", fr: "Viêt Nam", en: "Vietnam" },
  { code: "VU", fr: "Vanuatu", en: "Vanuatu" },
  { code: "WF", fr: "Wallis-et-Futuna", en: "Wallis & Futuna" },
  { code: "WS", fr: "Samoa", en: "Samoa" },
  { code: "YE", fr: "Yémen", en: "Yemen" },
  { code: "YT", fr: "Mayotte", en: "Mayotte" },
  { code: "ZA", fr: "Afrique du Sud", en: "South Africa" },
  { code: "ZM", fr: "Zambie", en: "Zambia" },
  { code: "ZW", fr: "Zimbabwe", en: "Zimbabwe" },
]

/** Retourne la liste triée alphabétiquement selon la langue active. */
export function sortedCountries(locale: "fr" | "en"): Country[] {
  return [...COUNTRIES].sort((a, b) => a[locale].localeCompare(b[locale], locale))
}
